#!/usr/bin/env bash
#
# Create the LARGE Sailors & Boats database — a marina three years wide.
#
#   ./create_database_large.sh                          # create sailors_and_boats_large.duckdb
#   ./create_database_large.sh --verify                 # create it, then try 11 forbidden inserts
#   ./create_database_large.sh /tmp/big.duckdb          # create one somewhere else
#   ./create_database_large.sh --force                  # replace an existing database
#   ./create_database_large.sh --regenerate             # rebuild database/sql_large/02_data.sql first
#
# Same schema, different rows. Two scripts run, in this order:
#
#     database/sql/01_schema.sql    the SHARED schema — unchanged, still the one
#                                   place every requirement R1-R10, P1-P3 and
#                                   D1-D2 is defined
#     database/sql_large/02_data.sql    235 sailors, 44 boats, 5000 reservations
#                                   across 2024-2026, generated by
#                                   src/generate_data_large.py
#
# database/sql/02_data.sql — the tutorial's 14 sailors and 10 reservations — is NOT run
# here, and is never modified: the notebooks and the test suite describe it, so
# it stays exactly as the textbook has it.
#
# Note the asymmetry with ./create_database.sh, which globs every database/sql/*.sql.
# This script names its two scripts explicitly, which is why the second dataset
# lives in database/sql_large/ — a file in database/sql/ would be picked up by BOTH.
#
# The database is a build artifact: this script is how you regenerate it. It
# will NOT overwrite an existing database unless you pass --force.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=_shared.sh
source "$PROJECT_DIR/_shared.sh"

case "${1:-}" in
    -h|--help) show_help "${BASH_SOURCE[0]}"; exit 0 ;;
esac

# Unlike the other scripts, the default here is the *second* database file.
resolve_db "${1:-}"
if [ "${DB_IS_DEFAULT:-1}" -eq 1 ]; then
    DB="$PROJECT_DIR/sailors_and_boats_large.duckdb"
else
    shift
fi

FORCE=0
VERIFY=0
REGENERATE=0
for arg in "$@"; do
    case "$arg" in
        --force)      FORCE=1 ;;
        --verify)     VERIFY=1 ;;
        --regenerate) REGENERATE=1 ;;
        *) echo "error: unknown option '$arg' (expected --force, --verify or --regenerate)" >&2; exit 2 ;;
    esac
done

cd "$PROJECT_DIR"

DB_ARG=""
[ "$DB" != "$PROJECT_DIR/sailors_and_boats_large.duckdb" ] && DB_ARG=" \"$DB\""

load_dotenv
require_uv
warn_if_locked "Marimo notebook" "marimo edit"
warn_if_locked "Streamlit app" "streamlit run app/streamlit_app.py"

# --- refuse to silently destroy data ----------------------------------------
if [ -f "$DB" ] && [ "$FORCE" -eq 0 ]; then
    echo "error: a database already exists at"                            >&2
    echo "         $DB"                                                   >&2
    echo                                                                  >&2
    if rows=$(uv run python -c "
import duckdb, sys
try:
    c = duckdb.connect(sys.argv[1], read_only=True)
    print('%d sailors, %d boats, %d reservations' % c.execute(
        'SELECT (SELECT count(*) FROM sailors), (SELECT count(*) FROM boats),'
        ' (SELECT count(*) FROM reserves)').fetchone())
except Exception:
    print('unreadable — it may be open in another program')
" "$DB" 2>/dev/null); then
        echo "       It currently holds $rows."                           >&2
    fi
    echo                                                                  >&2
    echo "Recreating it would discard anything added through the app. If"  >&2
    echo "that is what you want:"                                         >&2
    echo                                                                  >&2
    echo "    ./create_database_large.sh${DB_ARG} --force"                    >&2
    exit 3
fi

if [ "$REGENERATE" -eq 1 ]; then
    echo "Regenerating database/sql_large/02_data.sql from src/generate_data_large.py"
    uv run python src/generate_data_large.py
    echo
fi

if [ ! -f "database/sql_large/02_data.sql" ]; then
    echo "error: database/sql_large/02_data.sql is missing. Generate it with:"          >&2
    echo "    uv run python src/generate_data_large.py"                        >&2
    echo "or re-run this script with --regenerate."                        >&2
    exit 4
fi

announce "Creating the second database — 2024-2026, 235 sailors, 44 boats."

echo "  scripts, in order:"
echo "    database/sql/01_schema.sql     (shared, unchanged)"
echo "    database/sql_large/02_data.sql     (generated by src/generate_data_large.py)"
echo

export SAILORS_DB="$DB"

if [ "$VERIFY" -eq 1 ]; then
    uv run python src/build_database.py --sql database/sql/01_schema.sql database/sql_large/02_data.sql --verify
else
    uv run python src/build_database.py --sql database/sql/01_schema.sql database/sql_large/02_data.sql
fi

echo
echo "Done. Next:"
echo "    ./run_app.sh \"$DB\"        # the marina desk app, on the big dataset"
echo "    ./run_notebook_level_04.sh \"$DB\"   # any notebook, same schema"
echo
echo "The tutorial database (sailors_and_boats.duckdb) is untouched — the"
echo "notebooks' prose describes THAT one, so numbers will differ here."
